name: 'Get failed tests from XML results artifacts'
description: 'Get the list of failed tests from a dotnet test XML results file'
author: 'James Christou'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  run_name:
    description: 'This name is used to find the artifacts for your test results'
    required: true
  github_token:
    description: 'The token used for this workflow'
    required: true

# Define your outputs here.
outputs:
  failed_tests:
    description:
      'A list of the fully qualified names of the failed tests which can then be
      used as the filter for the next test run attempt'

runs:
  using: node20
  main: dist/index.js
